name: Notebook Validation

on:
  push:
    paths:
      - '**.ipynb'
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  validate-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbconvert
          
      - name: Validate notebooks
        run: |
          find . -name "*.ipynb" -not -path "*/\.*" -exec jupyter nbconvert --to notebook --execute {} \; 